title:            Intigold Mines Ltd.
description:      "News Releases"
logo:             IntigoldLogo.png
favicon:          favicon.ico
disqus_shortname: leighakin
# Assign a default image for your site's header and footer
default_bg:       3D-Nature-Autun-Fall-Wallpaper.jpg
search:           true
share:            true
# Read Time is a calculator tp provide post read-time based on word count. Usage is recommended.
readtime:         true
# Turn on or off the fin animations in the header and footer
animated_fins:	  true
# Specify the fin color in RGB value
fin_color:        "255,255,255"
# Change url to your domain. Leave localhost server or blank when working locally.
url:              http://intigold.github.io/Intigold.github.io-news

# Owner/author information
owner:
  name:           Intigold
  avatar:         perustatue.jpg
  email:          intigold.ltd@gmail.com
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    INTIGOLD MINES LTD. is a Canadian junior mining company trading on the TSX Venture Exchange under the symbol “IGD”. The Company has a proven management team and extensive connections to projects and financing. Intigold is focused on maximizing shareholder value through identifying and developing early stage gold and silver deposits.

  twitter:        Intigold
  facebook:       intigold
  github:         Intigold
  stackexchange:  
  linkedin:       
  instagram:      
  flickr:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    https://plus.google.com/u/2/106838958942387229548

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-51395459-1
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Define Navigation
navigation:
 - title: Home
   url: http://intigold.github.io/index.html
 - title: Projects
   url: /projects.html
 - title: About
   url: /about.html
 - title: Contact
   url: /contact.html
   
# Links to include in footer navigation
# For external links add external: true
links:
  - title: Home
    url: /
    external: false
    icon: home
  - title: 
    url: 
  - title: Categories
    url: /categories
  - title: Tags
    url: /tags
  - title: 
    url: 

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Canada/Vancouver
future:      true
pygments:    true
markdown:    kramdown
paginate:    6
paginate_path: "page:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
